export const SIGN_UP = "SIGN_UP";
export const SIGN_IN = "SIGN_IN";
export const LOGOUT = "LOGOUT";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILED = "AUTH_FAILED";
export const GET_ME = "GET_ME";
export const UPDATE_MY_PROFILE = "UPDATE_MY_PROFILE";

export const GET_MY_TASKS = "GET_MY_TASKS";
export const CREATE_TASK = "CREATE_TASK";
export const UPDATE_TASK = "UPDATE_TASK";
export const DELETE_TASK = "DELETE_TASK";
export const TASKS_ERROR = "TASKS_ERROR";

export const GET_MY_GROUPS = "GET_MY_GROUPS";
export const CREATE_GROUP = "CREATE_GROUP";
export const GET_GROUP_INFO = "GET_GROUP_INFO";
export const GROUPING_ERROR = "GROUPING_ERROR";

export const GET_MY_INVITATIONS = "GET_MY_INVITATIONS";
export const GET_INVITATION_INFO = "GET_INVITATION_INFO";
export const RESET_CURRENT_INVITATION = "RESET_CURRENT_INVITATION";
export const SEND_GROUP_INVITATION = "SEND_GROUP_INVITATION";
export const ACCEPT_INVITATION = "ACCEPT_INVITATION";
export const REJECT_INVITATION = "REJECT_INVITATION";
export const INVITATIONS_ERROR = "INVITATIONS_ERROR";

export const CREATE_NEW_PROJECT = "CREATE_NEW_PROJECT";
export const GET_PROJECT_INFO = "GET_PROJECT_INFO";
export const PROJECTS_ERROR = "PROJECTS_ERROR";

export const GET_ALL_USERS = "GET_ALL_USERS";
export const DELETE_USER = "DELETE_USER";
export const ADMIN_ERROR = "ADMIN_ERROR";

export const CLEAR_DB = "CLEAR_DB";
export const OWNER_ERROR = "OWNER_ERROR";

export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
export const SET_IS_LOADING = "SET_IS_LOADING";
