export const SIGN_UP = "SIGN_UP"
export const SIGN_IN = "SIGN_IN"
export const LOGOUT = "LOGOUT"
export const AUTH_SUCCESS = "AUTH_SUCCESS"
export const AUTH_FAILED = "AUTH_FAILED"
export const GET_ME = "GET_ME"
export const UPDATE_MY_PROFILE = "UPDATE_MY_PROFILE"

export const GET_MY_TASKS = "GET_MY_TASKS"
export const CREATE_TASK = "CREATE_TASK"
export const UPDATE_TASK = "UPDATE_TASK"
export const DELETE_TASK = "DELETE_TASK"
export const TASKS_ERROR = "TASKS_ERROR"